spring:

  profiles:
    active:
      - swagger

  data:
    mongodb:
      uri: ${MONGODB_URI}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG