spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  profiles:
    include:
      - oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG