spring:

  profiles:
    active:
      - s3
      - swagger

  data:
    mongodb:
      uri: ${MONGODB_URI}
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    port: 9200
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: 6379
    host: ${REDIS_URI}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG